[package]
name = "reg_explorer_dead_acqu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winreg = "0.10.1"

[target.'cfg(windows)'.dependencies]
nt-hive = "0.2.0"
datetime = "0.5.2"